### ISSUE TITLE
[FEAT] Virtual DB

### ISSUE THREAD

**Issue by CookieHCl** [CookieHCl/satisfactory-planner#2]
학생은 돈이 없다 API call을 줄이자

# 개요

이게 맞는 길이긴 함  
로컬에서 DB 프록시를 돌리고 거기랑만 소통해요

# 우선순위

없음  
하지말자  
귀찮어  
너가하셈

## Stage 1

DB 프록시 기능

- [ ] DB 프록시 추가
  - [ ] 웹앱 시작할 때 전부 fetch
  - [ ] 각 페이지는 API call하지 않고 전부 DB 프록시한테 요청보냄
  - [ ] DB 프록시는 요청받은거 확인해서 맨 처음 fetch받았을때랑 변경사항을 기록
- [ ] 각 페이지마다 Save 버튼 추가
  - [ ] Save 버튼을 누르면 DB 프록시는 지금까지 있었던 모든 변경사항을 PUSH (PUSH API 아님)

단점: 두 사람이 동시에 보면 동기화가 안 됨  
그래서 밑의 작업 필요

## Stage 2

자동세이브 기능

- [ ] [visibilitychange](https://developer.mozilla.org/ko/docs/Web/API/Document/visibilitychange_event) 이벤트 써서 꺼졌을 때 세이브
- [ ] 1분(?)마다 세이브

단점: 두 사람이 1분 이내로 수정하면 동기화가 안 됨  
그래서 밑의 작업 필요

## Stage 3

진짜 동기화

- [ ] 어떻게 함?
- [ ] 챗지피티 도와줘요
